# Lab 7 - TensorFlow

Welcome to this week's lab on TensorFlow! In this lab, you are going to explore TensorFlow, a popular open-source library for numerical computation and machine learning. TensorFlow provides a comprehensive, flexible ecosystem of tools, libraries, and community resources that lets researchers push the state-of-the-art in ML, and developers easily build and deploy ML-powered applications.

## Part 1: Getting Started with TensorFlow
First, ensure you have TensorFlow installed in your environment. You can either use a virtual environment or docker. Check out the TensorFlow's installation guide: https://www.tensorflow.org/install

### Basic Concepts
#### Tensors
The core unit of data in TensorFlow is a tensor. A tensor consists of a set of primitive values shaped into an array of any number of dimensions.

In [1]:
import tensorflow as tf

# Create a tensor
tensor = tf.constant([[1, 2], [3, 4]])
print(tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


#### Operations
You can perform operations on tensors like addition, multiplication, and matrix operations.

In [2]:
# Addition
tensor_add = tensor + 5
print(tensor_add)

# Multiplication
tensor_mul = tensor * 2
print(tensor_mul)

tf.Tensor(
[[6 7]
 [8 9]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)


#### Building a Simple Model
TensorFlow makes it easy to build models through layers and models API, typically using the Keras API. Learn more about Keras: https://keras.io/getting_started/

In [3]:
# Define a simple Sequential model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=(None, 5)),
    tf.keras.layers.Dense(1)
])

model.summary()

#model.compile(optimizer='adam', loss='mean_squared_error')

C:\ProgramData\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, None, 10)       │            60 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, None, 1)        │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 71 (284.00 B)

 Trainable params: 71 (284.00 B)

 Non-trainable params: 0 (0.00 B)

1. Find out about layers types in Keras documentation. Briefly explain about the `Dense` layer.
2. What does `model.summary()` show?
3. What does `model.compile` do?
4. What does optimizer do?
5. What is `loss`?

1. `Dense` is a densely-connected Neural Network layer. Operation is output=activation(dot (inpu, kernel)+bias), 
2. `model.summary` shows name of model, and information for each layer: names, type, # of parameters, and output shape.
3. `model.compile` Configures model with losses and metrics.
4. An `optimizer` helps to adjust weights and biases of the neural network to minimize error/loss.
5. `Loss` is the error. More loss = worse performance.

## Part 2: Implement a Simple TensorFlow Example

Let's build a simple model that learns to add two numbers. Partial codes are provided for you to complete them.

### Task 1: Generate Data
First, we need data to train our model. For simplicity, we you will generate synthetic data.

In [4]:
import numpy as np

# Generate random data
inputs = np.random.random((1000, 2))
sums = np.sum(inputs, axis=1, keepdims=True)

print("inputs", inputs[:5], "\nsums:", sums[:5])

inputs [[0.10903965 0.16722097]
 [0.1772709  0.17480367]
 [0.99987058 0.86986265]
 [0.81358068 0.75416611]
 [0.09829037 0.33890617]] 
sums: [[0.27626061]
 [0.35207457]
 [1.86973323]
 [1.56774679]
 [0.43719654]]


### Task 2: Build a Model
Now, you need to build a simple model for this task. We would need a model with the following architecture:
1. Number of Layers: 2
2. Layer 1:
      
      2.1 Type: `Dense`
      
      2.2 Neurone: `64`
      
      2.3: Activation Function: `relu`
3. Layer 2:

      3.1 Type: `Dense`
4. Optimizer: `adam`
5. Loss Function: `mean_squared_error`
    

In [8]:
# Define the model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64)
])

# Compile the model
#model.compile(?)
model.compile(optimizer='adam', loss='mean_squared_error')

In [9]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

### Task 3: Train the Model
With your data and model ready, you can train the model. I suggest training for 10 epochs with batch size of 32. You can change these if you wish.

In [12]:
# Train the model
model.fit(inputs, sums, 10, 32)

Epoch 1/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.9242
Epoch 2/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0357
Epoch 3/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0194
Epoch 4/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0099
Epoch 5/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0049
Epoch 6/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0019
Epoch 7/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1724e-04
Epoch 8/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.3658e-04
Epoch 9/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.5207e-04
Epoch 10/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.7812e-05
Epoch 11/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.0930e-05
Epoch 12/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.7952e-05
Epoch 13/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.7041e-05
Epoch 14/32
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.7989e-05
Epoch 15/32
100/100 ━━━━━

### Task 4: Test the Model
Finally, you can test your model with some new data.

In [18]:
# Test data
test_data = np.array([[1, 2], [4, 5], [21, 21]])

# Prediction
predictions = model.predict(test_data)

# Show Predictions
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 458ms/step
[[ 3.0011148  2.999057   2.9994533  3.0029166  2.9997246  3.0010574
   3.0024693  3.0032425  3.0015814  2.9994433  3.0022867  3.0001376
   3.0023272  3.0015523  3.0015721  3.0022922  3.0024166  3.001724
   3.00236    3.000422   3.0021155  3.001571   3.0007298  3.0023093
   3.001882   3.001564   3.0028806  3.0026262  2.9994826  3.001513
   3.0013704  3.0039003  3.0014768  3.0032833  3.001938   3.0035055
   3.0016353  3.0031536  3.00288    3.0011816  3.0013049  3.001851
   3.0015254  3.0041277  3.0027375  3.002152   3.0030348  3.0014539
   3.0021214  3.0013742  3.0026424  3.001548   3.0032885  2.9990945
   3.0017006  3.0026436  3.0025973  2.9995177  3.0026412  3.0011213
   3.0030186  3.0022912  3.0035825  3.0014055]
 [ 9.006743   8.999484   9.000732   9.009243   9.004343   9.003428
   9.008421   9.012454   9.009614   9.000968   9.005495   9.000172
   9.012111   9.005232   9.011126   9.006776   9.009685   9.008781
   9.010754   9.005512   9.010027   

## Submission
Submit a link to your completed Jupyter Notebook file hosted on your private GitHub repository through the submission link in Blackboard.